version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(gh-actions):"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(npm):"

  # Enable version updates for Docker in /.devcontainer
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `.devcontainer` directory
    directory: "/.devcontainer/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(docker):"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `.devcontainer` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(docker):"
